### ISSUE TITLE
Ultraschall Soundboard 1.9.6 does not appear in Reaper on Windows

### ISSUE THREAD

**Issue by svenwiegand** [Ultraschall/Soundboard#12]
Following configuration:
- Windows 10 64-Bit
- Reaper 5.04 64-Bit
- SWS 2.8.1 64-Bit
- Ultraschall 1.3 for Windows
- Ultraschall Soundboard 1.9.6

I've copied the soundboard to `C:\Program Files\Steinberg\VstPlugins` and explicitly added the path to the reaper VST plug-in path. As I were not sure whether I need to copy only the DLL or the ZIP file I've copied both to the directory mentioned above. But even if I try them alone, the VST plugin isn't shown.

I've added a soundboard track, but when I open the Soundboard tab Reaper shows the error message "The following effect plug-in could not be loaded: VSTi: Soundboard (Ultraschall)". Even if I try to add the plug-in manually I get a huge list of plug-ins, but the soundboard plug-in is not listed.

I've also tried with 32-bit Reaper with the same result.

**Comment by danlin** [comment]
> I've added a soundboard track, but when I open the Soundboard tab Reaper shows the error message "The following effect plug-in could not be loaded: VSTi: Soundboard (Ultraschall)". Even if I try to add the plug-in manually I get a huge list of plug-ins, but the soundboard plug-in is not listed.

Can you try to add the Soundboard VST manually like other VST Plugins in Reaper. The Ultraschall Menus are designed for MAC OS X. As i know Windows use other naming of VST Plugins.

**Comment by svenwiegand** [comment]
On Windows 7 I've made a little progress. Here is what I've done:
- Copy the `Soundboard.dll` into Reaper's `Plugins\FX` directory
- Bring up `Options > Preferences > Plug-ins > VST` and click the `Clear cache/re-scan` button. 
- This results in an error box saying that `msvcp140.dll` is missing
- Download and install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/de-de/download/details.aspx?id=48145)
- Again pressing the `Clear cache/re-scan` button does no longer bring the error message
- Create a soundboard track and -- voila -- I get the soundboard VST and can start it's GUI
- **But:** As soon as I select a directory in the Soundboard GUI Reaper's VST host 32 crashes -- this happens no matter whether I install the 32- or 64-bit Redistributables for Visual Studio 2015.

**Assumption:** There is some kind of 32 vs. 64 bit issue

On **Windows 10 64-bit** the situation is completely different: I can follow exactly the step 1 and 2 described above. The rescan will not bring an error message, but the soundboard effect is not available. I still get the "The following effect plug-in could not be loaded: VSTi: Soundboard (Ultraschall)". Even if I try to manually add a instrument to an audio track the soundboard isn't listed neither in the "VSTi" nor in the "VST" section.

**Comment by danlin** [comment]
Ok thanks for the good Reports. I check this soon.

**Comment by svenwiegand** [comment]
See my latest debugging results in #13.

**Comment by danlin** [comment]
try the new installer
