### ISSUE TITLE
Soundboard crashes on Windows 10

### ISSUE THREAD

**Issue by svenwiegand** [Ultraschall/Soundboard#13]
I am using the 1.9.6 Windows standalone app on Windows 10 Home. I was able to use exactly this version on another laptop, but on my new one (Dell XPS 13 with 4k display) it crashes as soon as I select a folder.

I can start the app, bring up the settings, select the output device and the test sound works. 

But if I click the folder icon in the main window, choose a folder from the upcoming picker and press the picker's OK button the Soundboard app crashes.

I already tried to make file access as easy as possible by creating a directory without spaces in it's name ("C:\temp\soundboard") and putting only two wav-files in there.

Any ideas?

**Comment by svenwiegand** [comment]
At first sorry for reporting the same issue as in ticket #12 -- I wasn't aware, that I've also had the crash on directory selection there -- I'm really getting old...

I've debugged the soundboard (man, haven't used Visual Studio since 2004...) and found the part causing the crash: `SoundboardTableComponent::paintCell` is called with a `rowNumber` which is one higher than the actual number of rows. So I was able to build me a workaround version by just putting a  `if (rowNumber >= processor.numPlayers()) return;` to the beginning of the method. With this version I can now use the soundboard again.

Here's the strange thing: I still don't understand why it is working in some cases and in some others not. In all cases I am opening exactly the same directory from my dropbox with only two flac-files in it. Here's a consolidated list of what I've seen:

* **Computer 1 -- Standalone App:** Everything is working fine.
* **Computer 1 -- VST plug-in in Reaper:** Crash when selecting the directory.
* **Computer 2 -- Standalone App:** Crash when selecting the directory (I've copied the `soundboard.exe` from computer 1, so it is definitely the same).

Both computers are on Windows 10 including the latest November update. Computer 1 is Windows 10 Pro and Computer 2 is Windows 10 home.

**Comment by svenwiegand** [comment]
Just for information. I've compiled an x64 version with the workaround described above applied to the code and now even the plug-in works fine for me on all systems.

**Comment by jprjr** [comment]
@svenwiegand Is there a way you can share that x64 build you've produced? I'd be really thankful for it!

**Comment by svenwiegand** [comment]
@jprjr checkout this one: [Soundboardx64_dll.zip](https://github.com/Ultraschall/Soundboard/files/254393/Soundboardx64_dll.zip)

**Comment by danlin** [comment]
win 64 build with some bugfixes commig soon

**Comment by danlin** [comment]
https://github.com/Ultraschall/Soundboard/releases/tag/V1.9.9-beta.1
