### ISSUE TITLE
Pause not working over OSC

### ISSUE THREAD

**Issue by bastibl** [Ultraschall/Soundboard#19]
Hallo,
erstmal danke fuer eure Arbeit am Soundboard.

Ich hab's gerade mal mit TouchOSC probiert. Es funktioniert alles super, bis auf den Pause-Knopf.
(Ich benutze Ultraschall v2.2.2 mit Soundboard v1.9.9).

Ich hab mal kurz in den Code geschaut, weiss aber nicht wie man's kompiliert und wie man die installierte Version ersetzt. Ist vlt. einfach hier die Negation falsch?
https://github.com/Ultraschall/Soundboard/blob/db1f82d63dd23b23b4071bc7b0e3aceccd00d1be/Source/Plugin/PluginProcessor.cpp#L592

**Comment by danlin** [comment]
Jup wird gefixt! Danke!

**Comment by heikopanjas** [comment]
fixed in release 3.0
